/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const AppSchema = z.object({
  string_vaue: z.string().nullable(),
  integer_value: z.number().nullable(),
  boolean_value: z.boolean().nullable(),
  array_value: z.array(z.unknown()).nullable(),
  hash_value: z.record(z.string(), z.unknown()).nullable()
});

export type App = z.infer<typeof AppSchema>;
