/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const ArraysAndHashesSchema = z.object({
  simple_array: z.array(z.string()),
  number_array: z.array(z.number()),
  nested_array: z.array(z.array(z.string())),
  string_hash: z.record(z.string(), z.string()),
  mixed_hash: z.record(z.string(), z.number()),
  array_of_hashes: z.array(z.record(z.string(), z.string())),
  complex_hash: z.record(z.string(), z.array(z.number()))
});

export type TArraysAndHashesSchema = z.infer<typeof ArraysAndHashesSchema>;
