/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const ApiV1ComplexNestedUserStatusEnum = z.enum(['active', 'inactive', 'suspended', 'pending']);

export type TApiV1ComplexNestedUserStatusEnum = z.infer<typeof ApiV1ComplexNestedUserStatusEnum>;

export const ApiV1ComplexNestedAddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  zip_code: z.string(),
  country: z.string()
});

export type TApiV1ComplexNestedAddressSchema = z.infer<typeof ApiV1ComplexNestedAddressSchema>;

export const ApiV1ComplexNestedContactInfoSchema = z.object({
  email: z.string(),
  phone: z.string().nullable(),
  address: ApiV1ComplexNestedAddressSchema
});

export type TApiV1ComplexNestedContactInfoSchema = z.infer<typeof ApiV1ComplexNestedContactInfoSchema>;

export const ApiV1ComplexNestedMetadataSchema = z.object({
  tags: z.array(z.string()),
  scores: z.record(z.string(), z.number()),
  created_at: z.string(),
  updated_at: z.string().nullable()
});

export type TApiV1ComplexNestedMetadataSchema = z.infer<typeof ApiV1ComplexNestedMetadataSchema>;

export const ApiV1ComplexNestedSchema = z.object({
  id: z.number(),
  name: z.string(),
  status: ApiV1ComplexNestedUserStatusEnum,
  contact_info: ApiV1ComplexNestedContactInfoSchema,
  metadata: ApiV1ComplexNestedMetadataSchema,
  roles: z.array(z.string()),
  is_verified: z.boolean()
});

export type TApiV1ComplexNestedSchema = z.infer<typeof ApiV1ComplexNestedSchema>;
