/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const SearchResultMatchSchema = z.object({
  score: z.number(),
  highlight: z.string()
});

export type TSearchResultMatchSchema = z.infer<typeof SearchResultMatchSchema>;

export const SearchResultSchema = z.object({
  result_id: z.union([z.string(), z.number()]),
  title: z.string(),
  match_info: SearchResultMatchSchema.nullable(),
  tags: z.array(z.string()),
  category: z.union([z.string(),z.number(),z.number()])
});

export type TSearchResultSchema = z.infer<typeof SearchResultSchema>;
