/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const Match = z.object({
  score: z.number(),
  highlight: z.string()
});

export type TMatch = z.infer<typeof Match>;

export const SearchResult = z.object({
  result_id: z.union([z.string(), z.number()]),
  title: z.string(),
  match_info: Match.nullable(),
  tags: z.array(z.string()),
  category: z.union([z.string(),z.number(),z.number()])
});

export type TSearchResult = z.infer<typeof SearchResult>;
