/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const UserStatus = z.enum(['active', 'inactive', 'suspended', 'pending']);

export type TUserStatus = z.infer<typeof UserStatus>;

export const Address = z.object({
  street: z.string(),
  city: z.string(),
  zip_code: z.string(),
  country: z.string()
});

export type TAddress = z.infer<typeof Address>;

export const ContactInfo = z.object({
  email: z.string(),
  phone: z.string().nullable(),
  address: Address
});

export type TContactInfo = z.infer<typeof ContactInfo>;

export const Metadata = z.object({
  tags: z.array(z.string()),
  scores: z.record(z.string(), z.number()),
  created_at: z.string(),
  updated_at: z.string().nullable()
});

export type TMetadata = z.infer<typeof Metadata>;

export const ComplexNested = z.object({
  id: z.number(),
  name: z.string(),
  status: UserStatus,
  contact_info: ContactInfo,
  metadata: Metadata,
  roles: z.array(z.string()),
  is_verified: z.boolean()
});

export type TComplexNested = z.infer<typeof ComplexNested>;
