/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const Member = z.object({
  id: z.number(),
  name: z.string(),
  role: z.string()
});

export type TMember = z.infer<typeof Member>;

export const Team = z.object({
  team_name: z.string(),
  members: z.array(Member)
});

export type TTeam = z.infer<typeof Team>;

export const Department = z.object({
  dept_name: z.string(),
  teams: z.array(Team)
});

export type TDepartment = z.infer<typeof Department>;

export const Organization = z.object({
  org_name: z.string(),
  departments: z.array(Department),
  employee_count: z.number()
});

export type TOrganization = z.infer<typeof Organization>;
