/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const OrganizationDepartmentTeamMemberSchema = z.object({
  id: z.number(),
  name: z.string(),
  role: z.string()
});

export type TOrganizationDepartmentTeamMemberSchema = z.infer<typeof OrganizationDepartmentTeamMemberSchema>;

export const OrganizationDepartmentTeamSchema = z.object({
  team_name: z.string(),
  members: z.array(OrganizationDepartmentTeamMemberSchema)
});

export type TOrganizationDepartmentTeamSchema = z.infer<typeof OrganizationDepartmentTeamSchema>;

export const OrganizationDepartmentSchema = z.object({
  dept_name: z.string(),
  teams: z.array(OrganizationDepartmentTeamSchema)
});

export type TOrganizationDepartmentSchema = z.infer<typeof OrganizationDepartmentSchema>;

export const OrganizationSchema = z.object({
  org_name: z.string(),
  departments: z.array(OrganizationDepartmentSchema),
  employee_count: z.number()
});

export type TOrganizationSchema = z.infer<typeof OrganizationSchema>;
