/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const UrlImageHash = z.object({
  url: z.string(),
  width: z.number(),
  height: z.number()
});

export type TUrlImageHash = z.infer<typeof UrlImageHash>;

export const ApplicationResearchArea = z.object({
  id: z.number(),
  name: z.string()
});

export type TApplicationResearchArea = z.infer<typeof ApplicationResearchArea>;

export const UniversityInfo = z.object({
  id: z.number(),
  name: z.string(),
  slug: z.string(),
  country_code: z.string().nullable(),
  claimed: z.boolean(),
  logo: UrlImageHash,
  banner_video: UrlImageHash,
  banner_image: UrlImageHash,
  research_areas: z.array(ApplicationResearchArea),
  more_research_areas: z.array(ApplicationResearchArea)
});

export type TUniversityInfo = z.infer<typeof UniversityInfo>;
