/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const OrderStatus = z.enum(['pending', 'processing', 'shipped', 'delivered', 'cancelled']);

export type TOrderStatus = z.infer<typeof OrderStatus>;

export const Priority = z.enum(['low', 'medium', 'high', 'urgent']);

export type TPriority = z.infer<typeof Priority>;

export const OrderResponse = z.object({
  id: z.string(),
  status: OrderStatus,
  priority: Priority,
  amount: z.number(),
  metadata: z.record(z.string(), z.string())
});

export type TOrderResponse = z.infer<typeof OrderResponse>;
