/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const OrderStatusEnum = z.enum(['pending', 'processing', 'shipped', 'delivered', 'cancelled']);

export type TOrderStatusEnum = z.infer<typeof OrderStatusEnum>;

export const OrderResponsePriorityEnum = z.enum(['low', 'medium', 'high', 'urgent']);

export type TOrderResponsePriorityEnum = z.infer<typeof OrderResponsePriorityEnum>;

export const OrderResponseSchema = z.object({
  id: z.string(),
  status: OrderStatusEnum,
  priority: OrderResponsePriorityEnum,
  amount: z.number(),
  metadata: z.record(z.string(), z.string())
});

export type TOrderResponseSchema = z.infer<typeof OrderResponseSchema>;
