/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const ApiV1ResponsesUserProfileSchema = z.object({
  id: z.number(),
  username: z.string(),
  email: z.string(),
  verified: z.boolean()
});

export type TApiV1ResponsesUserProfileSchema = z.infer<typeof ApiV1ResponsesUserProfileSchema>;
