/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const UserProfile = z.object({
  id: z.number(),
  username: z.string(),
  email: z.string(),
  verified: z.boolean()
});

export type TUserProfile = z.infer<typeof UserProfile>;
