/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const PayloadResultResultTypeEnum = z.enum(['animal', 'plant', 'human']);

export type TPayloadResultResultTypeEnum = z.infer<typeof PayloadResultResultTypeEnum>;

export const PayloadResultSchema = z.object({
  id: z.union([z.string(), z.number()]),
  name: z.string().nullable(),
  result_type: PayloadResultResultTypeEnum
});

export type TPayloadResultSchema = z.infer<typeof PayloadResultSchema>;

export const PayloadSchema = z.object({
  results: z.array(PayloadResultSchema),
  is_success: z.boolean()
});

export type TPayloadSchema = z.infer<typeof PayloadSchema>;
