/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const ResultType = z.enum(['animal', 'plant', 'human']);

export type TResultType = z.infer<typeof ResultType>;

export const Result = z.object({
  id: z.union([z.string(), z.number()]),
  name: z.string().nullable(),
  result_type: ResultType
});

export type TResult = z.infer<typeof Result>;

export const Payload = z.object({
  results: z.array(Result),
  is_success: z.boolean()
});

export type TPayload = z.infer<typeof Payload>;
