/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const SimpleEnumEnum = z.enum(['red', 'green', 'blue']);

export type TSimpleEnumEnum = z.infer<typeof SimpleEnumEnum>;
