/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const SimpleEnum = z.enum(['red', 'green', 'blue']);

export type TSimpleEnum = z.infer<typeof SimpleEnum>;
