/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const SpecialTypesSchema = z.object({
  untyped_field: z.unknown(),
  any_field: z.union([z.string(),z.number(),z.number(),z.unknown()]),
  all_field: z.unknown(),
  class_of_field: z.unknown(),
  attached_field: z.unknown(),
  normal_field: z.string()
});

export type TSpecialTypesSchema = z.infer<typeof SpecialTypesSchema>;
