/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const StructWithAliasSchema = z.object({
  string_key_hash: z.record(z.string(), z.unknown()),
  string_key_array: z.array(z.string()),
  string_key_hash_array: z.array(z.record(z.string(), z.unknown()))
});

export type TStructWithAliasSchema = z.infer<typeof StructWithAliasSchema>;
