/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const UnionTypesSchema = z.object({
  string_or_number: z.union([z.string(), z.number()]),
  multiple_types: z.union([z.string(),z.number(),z.number()]),
  boolean_value: z.boolean(),
  nullable_string: z.string().nullable(),
  nullable_number: z.number().nullable(),
  array_of_strings_or_numbers: z.array(z.union([z.string(), z.number()]))
});

export type TUnionTypesSchema = z.infer<typeof UnionTypesSchema>;
