/**
/* This file is generated by Mochitype. Do not edit it by hand.
/**/

import { z } from 'zod';

export const MochitypesUsersTypeEnum = z.enum(['basic', 'advanced']);

export type TMochitypesUsersTypeEnum = z.infer<typeof MochitypesUsersTypeEnum>;

export const MochitypesUsersUserShowDetailsSchema = z.object({
  username: z.string().nullable(),
  id: z.number(),
  created_at: z.unknown(),
  type: MochitypesUsersTypeEnum
});

export type TMochitypesUsersUserShowDetailsSchema = z.infer<typeof MochitypesUsersUserShowDetailsSchema>;
